- alias: Config Folder sync with GitHub 
  id: config-folder-sync

  trigger:
    platform: template
    value_template: "{{ states.sensor.lubomirkamensky_home_assistantconfig_posledni_commit.last_changed > (states.sensor.config_gitpull_datetime.last_changed + timedelta(minutes=5)) }}"
    for: "00:00:15"
  action:
  - service: shell_command.git_push
  - service: mqtt.publish
    data:
      topic: "config/git_pull/datetime"
      payload: "{{ now() }}"