
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt:
  sensor: !include sensor/mqtt.yaml
shell_command:
  git_push: bash /config/shell/push.sh
  git_pull: bash /config/shell/pull.sh
  git_unstaged: bash /config/shell/unstaged.sh
template:
  - trigger:
      - platform: time_pattern
        minutes: /1
    action:
      - service: shell_command.git_unstaged
        response_variable: resp_data
    sensor:
      - name: "config_unstaged"
        unique_id: sensor_config_unstaged_files_num
        state: "{{ resp_data['stdout'] }}"
